#!perl
use strict;
use warnings;
use utf8;

use Acme::CPAN::Installer;
exit Acme::CPAN::Installer->new->run(@ARGV);

__END__

=head1 NAME

cpan-installer - an experimental cpan module installer

=head1 SYNOPSIS

  # install modules
  > cpan-installer install Module1 Module2 ...

  # from cpanfile if it exists
  > cpan-installer install

  # just like carton exec
  > cpan-installer exec perl ...

=head1 OPTIONS

  -w, --workers=N
        number of workers, default: 5
  -L, local-lib-contained=DIR
        install base, default: local/
  -g, --global
        install modules to global @INC instead of local-lib
      --mirror
        base url for the cpan mirror to use, default: http://www.cpan.org
      --cpanmetadb
        cpanmetadb url, default: https://cpanmetadb-provides.herokuapp.com
  -v, --version
        show version
  -h, --help
        show this help

=cut
