#!perl
use strict;
use warnings;
use utf8;

use App::cpm;
exit App::cpm->new->run(@ARGV);

__END__

=head1 NAME

cpm - a fast CPAN module installer

=head1 SYNOPSIS

  # install modules
  > cpm install Module1 Module2 ...

  # install modules with verbose messages
  > cpm install -v Module

  # from cpanfile (with cpanfile.snapshot if any)
  > cpm install

  # install module to global @INC istead of local/lib/perl5
  > cpm install -g Module

  # install modules as if version of your perl is 5.8.5
  # so that modules which are not core in 5.8.5 will be installed
  > cpm install --target-perl 5.8.5

=head1 OPTIONS

  -w, --workers=N
        number of workers, default: 5
  -L, --local-lib-contained=DIR
        install base, default: local/
  -g, --global
        install modules to global @INC instead of local-lib
  -v, --verbose
        verbose mode; you can see what is going on
      --target-perl=VERSION  (EXPERIMENTAL)
        install modules as if verison is your perl is VERSION
      --mirror=URL
        base url for the CPAN mirror to use, default: http://www.cpan.org
        you can use --mirror multiple times
      --color, --no-color
        turn on/off color output, default: on
      --test, --no-test
        run test cases, default: no
      --cpanfile=FILENAME
        specify "cpanfile" filename, default: cpanfile
      --snapshot=FILENAME
        specify "cpanfile.snapshot" filename, defualt: cpanfile.snapshot
  -V, --version
        show version
  -h, --help
        show this help

=cut
